version: "3"
services:
   redis:
      image: redis:alpine
      ports:
         - 6379:6379
      container_name: redis-container
   # postgres:
   #    images: postgres:alpine
   #    ports:
   #       - 5432:5432
   #    environment:
   #       - POSTGRES_PASSWORD=password
   #    container_name: postgres-container
